__include__: [
  '../dataset/tinyperson_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: ./output/pafdetr_r50vd_tinyperson
